application: kindlejotter
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /google426a21f73c36306d.html
  script: notebook.py

- url: /.*
  script: notebook.py
  login: required
